#ifndef HOUDINI_ENGINE_BIND_ENUM
#define HOUDINI_ENGINE_BIND_ENUM
#include "DebugSymbol.h" 

#include <godot_cpp/core/class_db.hpp>
#include <godot_cpp/classes/object.hpp>
#include <HoudiniApi.h>
VARIANT_ENUM_CAST(HAPI_AttributeTypeInfo)
VARIANT_ENUM_CAST(HAPI_AttributeOwner)
VARIANT_ENUM_CAST(HAPI_NodeType)
VARIANT_ENUM_CAST(HAPI_GeoType)
VARIANT_ENUM_CAST(HAPI_PartType)
VARIANT_ENUM_CAST(HAPI_ParmType)
VARIANT_ENUM_CAST(HAPI_InputType)
VARIANT_ENUM_CAST(HAPI_CurveType)
VARIANT_ENUM_CAST(HAPI_Result)
VARIANT_ENUM_CAST(HAPI_NodeFlags)
VARIANT_ENUM_CAST(HAPI_StorageType)
VARIANT_ENUM_CAST(HAPI_PrmScriptType)
VARIANT_ENUM_CAST(HAPI_StatusVerbosity)
VARIANT_ENUM_CAST(HAPI_StatusType)
VARIANT_ENUM_CAST(HAPI_RampType)
VARIANT_ENUM_CAST(HAPI_RSTOrder)
VARIANT_ENUM_CAST(HAPI_XYZOrder)
VARIANT_ENUM_CAST(HAPI_TCP_PortType)
VARIANT_ENUM_CAST(HAPI_ThriftSharedMemoryBufferType)
VARIANT_ENUM_CAST(HAPI_Permissions)
VARIANT_ENUM_CAST(HAPI_ChoiceListType)
VARIANT_ENUM_CAST(HAPI_PackedPrimInstancingMode)
VARIANT_ENUM_CAST(HAPI_InputCurveMethod)
VARIANT_ENUM_CAST(HAPI_InputCurveParameterization)
class HEBindEnum: public godot::Object{
    GDCLASS(HEBindEnum, godot::Object)
    static void _bind_methods(){
        BIND_ENUM_CONSTANT(HAPI_RESULT_SUCCESS);
        BIND_ENUM_CONSTANT(HAPI_RESULT_FAILURE);
        BIND_ENUM_CONSTANT(HAPI_RESULT_ALREADY_INITIALIZED);
        BIND_ENUM_CONSTANT(HAPI_RESULT_NOT_INITIALIZED);
        BIND_ENUM_CONSTANT(HAPI_RESULT_CANT_LOADFILE);
        BIND_ENUM_CONSTANT(HAPI_RESULT_PARM_SET_FAILED);
        BIND_ENUM_CONSTANT(HAPI_RESULT_INVALID_ARGUMENT);
        BIND_ENUM_CONSTANT(HAPI_RESULT_CANT_LOAD_GEO);
        BIND_ENUM_CONSTANT(HAPI_RESULT_CANT_GENERATE_PRESET);
        BIND_ENUM_CONSTANT(HAPI_RESULT_CANT_LOAD_PRESET);
        BIND_ENUM_CONSTANT(HAPI_RESULT_ASSET_DEF_ALREADY_LOADED);
        BIND_ENUM_CONSTANT(HAPI_RESULT_NO_LICENSE_FOUND);
        BIND_ENUM_CONSTANT(HAPI_RESULT_DISALLOWED_NC_LICENSE_FOUND);
        BIND_ENUM_CONSTANT(HAPI_RESULT_DISALLOWED_NC_ASSET_WITH_C_LICENSE);
        BIND_ENUM_CONSTANT(HAPI_RESULT_DISALLOWED_NC_ASSET_WITH_LC_LICENSE);
        BIND_ENUM_CONSTANT(HAPI_RESULT_DISALLOWED_LC_ASSET_WITH_C_LICENSE);
        BIND_ENUM_CONSTANT(HAPI_RESULT_DISALLOWED_HENGINEINDIE_W_3PARTY_PLUGIN);
        BIND_ENUM_CONSTANT(HAPI_RESULT_ASSET_INVALID);
        BIND_ENUM_CONSTANT(HAPI_RESULT_NODE_INVALID);
        BIND_ENUM_CONSTANT(HAPI_RESULT_USER_INTERRUPTED);
        BIND_ENUM_CONSTANT(HAPI_RESULT_INVALID_SESSION);

        BIND_ENUM_CONSTANT(HAPI_STATUSVERBOSITY_0);
        BIND_ENUM_CONSTANT(HAPI_STATUSVERBOSITY_1);
        BIND_ENUM_CONSTANT(HAPI_STATUSVERBOSITY_2);
        BIND_ENUM_CONSTANT(HAPI_STATUSVERBOSITY_ALL);
        BIND_ENUM_CONSTANT(HAPI_STATUSVERBOSITY_ERRORS);
        BIND_ENUM_CONSTANT(HAPI_STATUSVERBOSITY_WARNINGS);
        BIND_ENUM_CONSTANT(HAPI_STATUSVERBOSITY_MESSAGES);

        BIND_ENUM_CONSTANT(HAPI_TRS);
        BIND_ENUM_CONSTANT(HAPI_TSR);
        BIND_ENUM_CONSTANT(HAPI_RTS);
        BIND_ENUM_CONSTANT(HAPI_RST);
        BIND_ENUM_CONSTANT(HAPI_STR);
        BIND_ENUM_CONSTANT(HAPI_SRT);
        BIND_ENUM_CONSTANT(HAPI_RSTORDER_DEFAULT);

        BIND_ENUM_CONSTANT(HAPI_XYZ);
        BIND_ENUM_CONSTANT(HAPI_XZY);
        BIND_ENUM_CONSTANT(HAPI_YXZ);
        BIND_ENUM_CONSTANT(HAPI_YZX);
        BIND_ENUM_CONSTANT(HAPI_ZXY);
        BIND_ENUM_CONSTANT(HAPI_ZYX);
        BIND_ENUM_CONSTANT(HAPI_XYZORDER_DEFAULT);

        BIND_ENUM_CONSTANT(HAPI_STATUS_CALL_RESULT);
        BIND_ENUM_CONSTANT(HAPI_STATUS_COOK_RESULT);
        BIND_ENUM_CONSTANT(HAPI_STATUS_COOK_STATE);
        BIND_ENUM_CONSTANT(HAPI_STATUS_MAX);

        BIND_ENUM_CONSTANT(HAPI_TCP_PORT_ANY);
        BIND_ENUM_CONSTANT(HAPI_TCP_PORT_RANGE);
        BIND_ENUM_CONSTANT(HAPI_TCP_PORT_LIST);

        BIND_ENUM_CONSTANT(HAPI_THRIFT_SHARED_MEMORY_FIXED_LENGTH_BUFFER);
        BIND_ENUM_CONSTANT(HAPI_THRIFT_SHARED_MEMORY_RING_BUFFER);

        BIND_ENUM_CONSTANT(HAPI_PACKEDPRIM_INSTANCING_MODE_INVALID)
        BIND_ENUM_CONSTANT(HAPI_PACKEDPRIM_INSTANCING_MODE_DISABLED)
        BIND_ENUM_CONSTANT(HAPI_PACKEDPRIM_INSTANCING_MODE_HIERARCHY)
        BIND_ENUM_CONSTANT(HAPI_PACKEDPRIM_INSTANCING_MODE_FLAT)
        BIND_ENUM_CONSTANT(HAPI_PACKEDPRIM_INSTANCING_MODE_MAX)

        BIND_ENUM_CONSTANT(HAPI_STORAGETYPE_INVALID)
        BIND_ENUM_CONSTANT(HAPI_STORAGETYPE_INT)
        BIND_ENUM_CONSTANT(HAPI_STORAGETYPE_INT64)
        BIND_ENUM_CONSTANT(HAPI_STORAGETYPE_FLOAT)
        BIND_ENUM_CONSTANT(HAPI_STORAGETYPE_FLOAT64)
        BIND_ENUM_CONSTANT(HAPI_STORAGETYPE_STRING)
        BIND_ENUM_CONSTANT(HAPI_STORAGETYPE_UINT8)
        BIND_ENUM_CONSTANT(HAPI_STORAGETYPE_INT8)
        BIND_ENUM_CONSTANT(HAPI_STORAGETYPE_INT16)
        BIND_ENUM_CONSTANT(HAPI_STORAGETYPE_DICTIONARY)
        BIND_ENUM_CONSTANT(HAPI_STORAGETYPE_INT_ARRAY)
        BIND_ENUM_CONSTANT(HAPI_STORAGETYPE_INT64_ARRAY)
        BIND_ENUM_CONSTANT(HAPI_STORAGETYPE_FLOAT_ARRAY)
        BIND_ENUM_CONSTANT(HAPI_STORAGETYPE_FLOAT64_ARRAY)
        BIND_ENUM_CONSTANT(HAPI_STORAGETYPE_STRING_ARRAY)
        BIND_ENUM_CONSTANT(HAPI_STORAGETYPE_UINT8_ARRAY)
        BIND_ENUM_CONSTANT(HAPI_STORAGETYPE_INT8_ARRAY)
        BIND_ENUM_CONSTANT(HAPI_STORAGETYPE_INT16_ARRAY)
        BIND_ENUM_CONSTANT(HAPI_STORAGETYPE_DICTIONARY_ARRAY)

        BIND_ENUM_CONSTANT(HAPI_ATTRIBUTE_TYPE_INVALID)
        BIND_ENUM_CONSTANT(HAPI_ATTRIBUTE_TYPE_NONE)
        BIND_ENUM_CONSTANT(HAPI_ATTRIBUTE_TYPE_POINT)
        BIND_ENUM_CONSTANT(HAPI_ATTRIBUTE_TYPE_HPOINT)
        BIND_ENUM_CONSTANT(HAPI_ATTRIBUTE_TYPE_VECTOR)
        BIND_ENUM_CONSTANT(HAPI_ATTRIBUTE_TYPE_NORMAL)
        BIND_ENUM_CONSTANT(HAPI_ATTRIBUTE_TYPE_COLOR)
        BIND_ENUM_CONSTANT(HAPI_ATTRIBUTE_TYPE_QUATERNION)
        BIND_ENUM_CONSTANT(HAPI_ATTRIBUTE_TYPE_MATRIX3)
        BIND_ENUM_CONSTANT(HAPI_ATTRIBUTE_TYPE_MATRIX)
        BIND_ENUM_CONSTANT(HAPI_ATTRIBUTE_TYPE_ST)
        BIND_ENUM_CONSTANT(HAPI_ATTRIBUTE_TYPE_HIDDEN)
        BIND_ENUM_CONSTANT(HAPI_ATTRIBUTE_TYPE_BOX2)
        BIND_ENUM_CONSTANT(HAPI_ATTRIBUTE_TYPE_BOX)
        BIND_ENUM_CONSTANT(HAPI_ATTRIBUTE_TYPE_TEXTURE)
        BIND_ENUM_CONSTANT(HAPI_ATTRIBUTE_TYPE_MAX)

        BIND_ENUM_CONSTANT(HAPI_ATTROWNER_INVALID)
        BIND_ENUM_CONSTANT(HAPI_ATTROWNER_VERTEX)
        BIND_ENUM_CONSTANT(HAPI_ATTROWNER_POINT)
        BIND_ENUM_CONSTANT(HAPI_ATTROWNER_PRIM)
        BIND_ENUM_CONSTANT(HAPI_ATTROWNER_DETAIL)
        BIND_ENUM_CONSTANT(HAPI_ATTROWNER_MAX)

        BIND_ENUM_CONSTANT(HAPI_NODETYPE_ANY)
        BIND_ENUM_CONSTANT(HAPI_NODETYPE_NONE)
        BIND_ENUM_CONSTANT(HAPI_NODETYPE_OBJ)
        BIND_ENUM_CONSTANT(HAPI_NODETYPE_SOP)
        BIND_ENUM_CONSTANT(HAPI_NODETYPE_CHOP)
        BIND_ENUM_CONSTANT(HAPI_NODETYPE_ROP)
        BIND_ENUM_CONSTANT(HAPI_NODETYPE_SHOP)
        BIND_ENUM_CONSTANT(HAPI_NODETYPE_COP)
        BIND_ENUM_CONSTANT(HAPI_NODETYPE_VOP)
        BIND_ENUM_CONSTANT(HAPI_NODETYPE_DOP)
        BIND_ENUM_CONSTANT(HAPI_NODETYPE_TOP)

        BIND_ENUM_CONSTANT(HAPI_GEOTYPE_INVALID)
        BIND_ENUM_CONSTANT(HAPI_GEOTYPE_DEFAULT)
        BIND_ENUM_CONSTANT(HAPI_GEOTYPE_INTERMEDIATE)
        BIND_ENUM_CONSTANT(HAPI_GEOTYPE_INPUT)
        BIND_ENUM_CONSTANT(HAPI_GEOTYPE_CURVE)
        BIND_ENUM_CONSTANT(HAPI_GEOTYPE_MAX)
        
        BIND_ENUM_CONSTANT(HAPI_PARTTYPE_INVALID);
        BIND_ENUM_CONSTANT(HAPI_PARTTYPE_MESH);
        BIND_ENUM_CONSTANT(HAPI_PARTTYPE_CURVE);
        BIND_ENUM_CONSTANT(HAPI_PARTTYPE_VOLUME);
        BIND_ENUM_CONSTANT(HAPI_PARTTYPE_INSTANCER);
        BIND_ENUM_CONSTANT(HAPI_PARTTYPE_BOX);
        BIND_ENUM_CONSTANT(HAPI_PARTTYPE_SPHERE);
        BIND_ENUM_CONSTANT(HAPI_PARTTYPE_MAX);

        BIND_ENUM_CONSTANT(HAPI_INPUT_INVALID);
        BIND_ENUM_CONSTANT(HAPI_INPUT_TRANSFORM);
        BIND_ENUM_CONSTANT(HAPI_INPUT_GEOMETRY);
        BIND_ENUM_CONSTANT(HAPI_INPUT_MAX);

        BIND_ENUM_CONSTANT(HAPI_CURVETYPE_INVALID);
        BIND_ENUM_CONSTANT(HAPI_CURVETYPE_LINEAR);
        BIND_ENUM_CONSTANT(HAPI_CURVETYPE_NURBS);
        BIND_ENUM_CONSTANT(HAPI_CURVETYPE_BEZIER);
        BIND_ENUM_CONSTANT(HAPI_CURVETYPE_MAX);

        BIND_ENUM_CONSTANT(HAPI_PARMTYPE_INT);
        BIND_ENUM_CONSTANT(HAPI_PARMTYPE_MULTIPARMLIST);
        BIND_ENUM_CONSTANT(HAPI_PARMTYPE_TOGGLE);
        BIND_ENUM_CONSTANT(HAPI_PARMTYPE_BUTTON);
        BIND_ENUM_CONSTANT(HAPI_PARMTYPE_FLOAT);
        BIND_ENUM_CONSTANT(HAPI_PARMTYPE_COLOR);
        BIND_ENUM_CONSTANT(HAPI_PARMTYPE_STRING);
        BIND_ENUM_CONSTANT(HAPI_PARMTYPE_PATH_FILE);
        BIND_ENUM_CONSTANT(HAPI_PARMTYPE_PATH_FILE_GEO);
        BIND_ENUM_CONSTANT(HAPI_PARMTYPE_PATH_FILE_IMAGE);
        BIND_ENUM_CONSTANT(HAPI_PARMTYPE_NODE);
        BIND_ENUM_CONSTANT(HAPI_PARMTYPE_FOLDERLIST);
        BIND_ENUM_CONSTANT(HAPI_PARMTYPE_FOLDERLIST_RADIO);
        BIND_ENUM_CONSTANT(HAPI_PARMTYPE_FOLDER);
        BIND_ENUM_CONSTANT(HAPI_PARMTYPE_LABEL);
        BIND_ENUM_CONSTANT(HAPI_PARMTYPE_SEPARATOR);
        BIND_ENUM_CONSTANT(HAPI_PARMTYPE_PATH_FILE_DIR);
        BIND_ENUM_CONSTANT(HAPI_PARMTYPE_MAX);
        BIND_ENUM_CONSTANT(HAPI_PARMTYPE_INT_START);
        BIND_ENUM_CONSTANT(HAPI_PARMTYPE_INT_END);
        BIND_ENUM_CONSTANT(HAPI_PARMTYPE_FLOAT_START);
        BIND_ENUM_CONSTANT(HAPI_PARMTYPE_FLOAT_END);
        BIND_ENUM_CONSTANT(HAPI_PARMTYPE_STRING_START);
        BIND_ENUM_CONSTANT(HAPI_PARMTYPE_STRING_END);
        BIND_ENUM_CONSTANT(HAPI_PARMTYPE_PATH_START);
        BIND_ENUM_CONSTANT(HAPI_PARMTYPE_PATH_END);
        BIND_ENUM_CONSTANT(HAPI_PARMTYPE_NODE_START);
        BIND_ENUM_CONSTANT(HAPI_PARMTYPE_NODE_END);
        BIND_ENUM_CONSTANT(HAPI_PARMTYPE_CONTAINER_START);
        BIND_ENUM_CONSTANT(HAPI_PARMTYPE_CONTAINER_END);
        BIND_ENUM_CONSTANT(HAPI_PARMTYPE_NONVALUE_START);
        BIND_ENUM_CONSTANT(HAPI_PARMTYPE_NONVALUE_END);

        BIND_ENUM_CONSTANT(HAPI_PRM_SCRIPT_TYPE_INT);
        BIND_ENUM_CONSTANT(HAPI_PRM_SCRIPT_TYPE_FLOAT);
        BIND_ENUM_CONSTANT(HAPI_PRM_SCRIPT_TYPE_ANGLE);
        BIND_ENUM_CONSTANT(HAPI_PRM_SCRIPT_TYPE_STRING);
        BIND_ENUM_CONSTANT(HAPI_PRM_SCRIPT_TYPE_FILE);
        BIND_ENUM_CONSTANT(HAPI_PRM_SCRIPT_TYPE_DIRECTORY);
        BIND_ENUM_CONSTANT(HAPI_PRM_SCRIPT_TYPE_IMAGE);
        BIND_ENUM_CONSTANT(HAPI_PRM_SCRIPT_TYPE_GEOMETRY);
        BIND_ENUM_CONSTANT(HAPI_PRM_SCRIPT_TYPE_TOGGLE);
        BIND_ENUM_CONSTANT(HAPI_PRM_SCRIPT_TYPE_BUTTON);
        BIND_ENUM_CONSTANT(HAPI_PRM_SCRIPT_TYPE_VECTOR2);
        BIND_ENUM_CONSTANT(HAPI_PRM_SCRIPT_TYPE_VECTOR3);
        BIND_ENUM_CONSTANT(HAPI_PRM_SCRIPT_TYPE_VECTOR4);
        BIND_ENUM_CONSTANT(HAPI_PRM_SCRIPT_TYPE_INTVECTOR2);
        BIND_ENUM_CONSTANT(HAPI_PRM_SCRIPT_TYPE_INTVECTOR3);
        BIND_ENUM_CONSTANT(HAPI_PRM_SCRIPT_TYPE_INTVECTOR4);
        BIND_ENUM_CONSTANT(HAPI_PRM_SCRIPT_TYPE_UV);
        BIND_ENUM_CONSTANT(HAPI_PRM_SCRIPT_TYPE_UVW);
        BIND_ENUM_CONSTANT(HAPI_PRM_SCRIPT_TYPE_DIR);
        BIND_ENUM_CONSTANT(HAPI_PRM_SCRIPT_TYPE_COLOR);
        BIND_ENUM_CONSTANT(HAPI_PRM_SCRIPT_TYPE_COLOR4);
        BIND_ENUM_CONSTANT(HAPI_PRM_SCRIPT_TYPE_HUECIRCLE);
        BIND_ENUM_CONSTANT(HAPI_PRM_SCRIPT_TYPE_OPPATH);
        BIND_ENUM_CONSTANT(HAPI_PRM_SCRIPT_TYPE_OPLIST);
        BIND_ENUM_CONSTANT(HAPI_PRM_SCRIPT_TYPE_OBJECT);
        BIND_ENUM_CONSTANT(HAPI_PRM_SCRIPT_TYPE_OBJECTLIST);
        BIND_ENUM_CONSTANT(HAPI_PRM_SCRIPT_TYPE_RENDER);
        BIND_ENUM_CONSTANT(HAPI_PRM_SCRIPT_TYPE_SEPARATOR);
        BIND_ENUM_CONSTANT(HAPI_PRM_SCRIPT_TYPE_GEOMETRY_DATA);
        BIND_ENUM_CONSTANT(HAPI_PRM_SCRIPT_TYPE_KEY_VALUE_DICT);
        BIND_ENUM_CONSTANT(HAPI_PRM_SCRIPT_TYPE_LABEL);
        BIND_ENUM_CONSTANT(HAPI_PRM_SCRIPT_TYPE_RGBAMASK);
        BIND_ENUM_CONSTANT(HAPI_PRM_SCRIPT_TYPE_ORDINAL);
        BIND_ENUM_CONSTANT(HAPI_PRM_SCRIPT_TYPE_RAMP_FLT);
        BIND_ENUM_CONSTANT(HAPI_PRM_SCRIPT_TYPE_RAMP_RGB);
        BIND_ENUM_CONSTANT(HAPI_PRM_SCRIPT_TYPE_FLOAT_LOG);
        BIND_ENUM_CONSTANT(HAPI_PRM_SCRIPT_TYPE_INT_LOG);
        BIND_ENUM_CONSTANT(HAPI_PRM_SCRIPT_TYPE_DATA);
        BIND_ENUM_CONSTANT(HAPI_PRM_SCRIPT_TYPE_FLOAT_MINMAX);
        BIND_ENUM_CONSTANT(HAPI_PRM_SCRIPT_TYPE_INT_MINMAX);
        BIND_ENUM_CONSTANT(HAPI_PRM_SCRIPT_TYPE_INT_STARTEND);
        BIND_ENUM_CONSTANT(HAPI_PRM_SCRIPT_TYPE_BUTTONSTRIP);
        BIND_ENUM_CONSTANT(HAPI_PRM_SCRIPT_TYPE_ICONSTRIP);
        BIND_ENUM_CONSTANT(HAPI_PRM_SCRIPT_TYPE_GROUPRADIO);
        BIND_ENUM_CONSTANT(HAPI_PRM_SCRIPT_TYPE_GROUPCOLLAPSIBLE);
        BIND_ENUM_CONSTANT(HAPI_PRM_SCRIPT_TYPE_GROUPSIMPLE);
        BIND_ENUM_CONSTANT(HAPI_PRM_SCRIPT_TYPE_GROUP);

        BIND_ENUM_CONSTANT(HAPI_PERMISSIONS_NON_APPLICABLE);
        BIND_ENUM_CONSTANT(HAPI_PERMISSIONS_READ_WRITE);
        BIND_ENUM_CONSTANT(HAPI_PERMISSIONS_READ_ONLY);
        BIND_ENUM_CONSTANT(HAPI_PERMISSIONS_WRITE_ONLY);
        BIND_ENUM_CONSTANT(HAPI_PERMISSIONS_MAX);

        BIND_ENUM_CONSTANT(HAPI_CHOICELISTTYPE_NONE);
        BIND_ENUM_CONSTANT(HAPI_CHOICELISTTYPE_NORMAL);
        BIND_ENUM_CONSTANT(HAPI_CHOICELISTTYPE_MINI);
        BIND_ENUM_CONSTANT(HAPI_CHOICELISTTYPE_REPLACE);
        BIND_ENUM_CONSTANT(HAPI_CHOICELISTTYPE_TOGGLE);

        BIND_ENUM_CONSTANT(HAPI_NODEFLAGS_ANY);
        BIND_ENUM_CONSTANT(HAPI_NODEFLAGS_NONE);
        BIND_ENUM_CONSTANT(HAPI_NODEFLAGS_DISPLAY);
        BIND_ENUM_CONSTANT(HAPI_NODEFLAGS_RENDER);
        BIND_ENUM_CONSTANT(HAPI_NODEFLAGS_TEMPLATED);
        BIND_ENUM_CONSTANT(HAPI_NODEFLAGS_LOCKED);
        BIND_ENUM_CONSTANT(HAPI_NODEFLAGS_EDITABLE);
        BIND_ENUM_CONSTANT(HAPI_NODEFLAGS_BYPASS);
        BIND_ENUM_CONSTANT(HAPI_NODEFLAGS_NETWORK);
        BIND_ENUM_CONSTANT(HAPI_NODEFLAGS_OBJ_GEOMETRY);
        BIND_ENUM_CONSTANT(HAPI_NODEFLAGS_OBJ_CAMERA);
        BIND_ENUM_CONSTANT(HAPI_NODEFLAGS_OBJ_LIGHT);
        BIND_ENUM_CONSTANT(HAPI_NODEFLAGS_OBJ_SUBNET);
        BIND_ENUM_CONSTANT(HAPI_NODEFLAGS_SOP_CURVE);
        BIND_ENUM_CONSTANT(HAPI_NODEFLAGS_SOP_GUIDE);
        BIND_ENUM_CONSTANT(HAPI_NODEFLAGS_TOP_NONSCHEDULER);
        BIND_ENUM_CONSTANT(HAPI_NODEFLAGS_NON_BYPASS);

        BIND_ENUM_CONSTANT(HAPI_RAMPTYPE_INVALID);
        BIND_ENUM_CONSTANT(HAPI_RAMPTYPE_FLOAT);
        BIND_ENUM_CONSTANT(HAPI_RAMPTYPE_COLOR);
        BIND_ENUM_CONSTANT(HAPI_RAMPTYPE_MAX);

        BIND_ENUM_CONSTANT(HAPI_CURVEMETHOD_INVALID);
        BIND_ENUM_CONSTANT(HAPI_CURVEMETHOD_CVS);
        BIND_ENUM_CONSTANT(HAPI_CURVEMETHOD_BREAKPOINTS);
        BIND_ENUM_CONSTANT(HAPI_CURVEMETHOD_MAX);

        BIND_ENUM_CONSTANT(HAPI_CURVEPARAMETERIZATION_INVALID);
        BIND_ENUM_CONSTANT(HAPI_CURVEPARAMETERIZATION_UNIFORM);
        BIND_ENUM_CONSTANT(HAPI_CURVEPARAMETERIZATION_CHORD);
        BIND_ENUM_CONSTANT(HAPI_CURVEPARAMETERIZATION_CENTRIPETAL);
        BIND_ENUM_CONSTANT(HAPI_CURVEPARAMETERIZATION_MAX);
    }
};
#endif