name: Houdini Engine For Godot
run-name: Pre-build for each platform
on: 
  push:
    tags:
      - "Release-v*.*.*"
jobs:
  Mac-Build:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: brew install llvm
      - run: echo "$(brew --prefix llvm)/bin" >> $GITHUB_PATH
      - run: echo "CC=$(brew --prefix llvm)/bin/clang" >> $GITHUB_ENV
      - run: echo "CXX=$(brew --prefix llvm)/bin/clang++" >> $GITHUB_ENV
      - run: echo "LDFLAGS=\"-L/opt/homebrew/opt/llvm/lib ${LDFLAGS}\"" >> $GITHUB_ENV
      - run: echo "CPPFLAGS=\"-I/opt/homebrew/opt/llvm/include ${CPPFLAGS}\"" >> $GITHUB_ENV
      - run: export PATH="$(brew --prefix llvm)/bin:${PATH}"
      - run: git submodule update --init --recursive
      - run: pip install scons
      - run: scons --version
      - run: scons target=editor
      - run: cd project/addons && zip -r ../../HoudiniEngineForGodot-Macos.zip HoudiniEngineForGodot && cd ../..
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: macos
          path: HoudiniEngineForGodot-Macos.zip
  Linux-Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: git submodule update --init --recursive
      - run: pip install scons
      - run: scons --version
      - run: scons target=editor
      - run: cd project/addons && zip -r ../../HoudiniEngineForGodot-Linux.zip HoudiniEngineForGodot && cd ../..
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: linux
          path: HoudiniEngineForGodot-Linux.zip
  Windows-Build:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: git submodule update --init --recursive
      - run: pip install scons
      - run: scons --version
      - run: scons target=editor
      - run: Compress-Archive -Path project/addons/HoudiniEngineForGodot -DestinationPath HoudiniEngineForGodot-Windows.zip
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: HoudiniEngineForGodot-Windows.zip
  Release:
    runs-on: ubuntu-latest
    needs: [Linux-Build, Windows-Build, Mac-Build]
    steps:
      - name: Download
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - run: ls
      - run: ls artifacts
      - name: Release-Draft
        uses: softprops/action-gh-release@v2
        with: 
          name: Release ${{github.ref_name}}
          tag_name: ${{github.ref_name}}
          draft: true
          files: artifacts/**
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        