name: Houdini Engine For Godot
run-name: Pre-build for each platform
on: 
    push:
        branches:
            - main
jobs:
    Mac-Build:
        runs-on: macos-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v4
            - run: git submodule update --init --recursive
            - run: pip install scons
            - run: scons --version
            - run: scons target=editor